### ISSUE TITLE
backup: stylus font-size & line-height

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/ideas#105]
http://stylus-lang.com/try.html

```
//define default values (best to put this in the default.styl file)  
base-font-size = 16
base-line-height = 24

//This is the useful part: it compares the given value to the base values and calculates the correct output
font-size($fontValue = base-font-size, $baseFontValue = base-font-size, $baseLineValue = base-line-height)
  font-size   $fontValue px
  font-size   ($fontValue / $baseFontValue) rem
  line-height ($fontValue / $baseFontValue) * $baseLineValue
  line-height ($baseLineValue/$baseFontValue) * ($fontValue / $baseFontValue) rem

//Test mixin, adjust the value to see it in action
p
  font-size(20)
```

result

```css
p {
  font-size: 20px;
  font-size: 1.25rem;
  line-height: 30;
  line-height: 1.875rem;
}
```
