### ISSUE TITLE
Hicks - Simplest and Fastest CSS parser and processor

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/ideas#12]
very basic, just one of implementations that I tried. Just a proof of concept.

given css

``` css


:root {
  clr: #edc6ea;
  radius: 5px;
}

@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
  -o-border-radius: $radius;
  border-radius: $radius;
}

ul {
  padding: 123px;
  font-family: Arial;
}
h3 {
  padding: 123px;
  font-family: Arial;
}
ul {
  color: #ef3;
  font-family: Hanover;
}
h2 {
  color: #ef3;
  font-family: Hanover;
}

ul li > div {
  border-radius: radius;
  font-size: size;
  color: clr;
  border-radius: 12px;
}

ul li > div a.btn .big {
  color: black;
}

ul li > div a.click .something .bg {
  border-radius: radius;
  background: teal;
}
```

processing

``` js
var fs = require('fs');
var path = require('path');
var balanced = require('balanced-match');

var css = fs.readFileSync(path.join(__dirname, 'fixtures/advanced3.css'), 'utf8');

function hicks(res, json) {
  var before = res.pre.replace(/[\r\n]*/g, '').trim();
  var body = res.body.replace(/[\r\n]*/g, '').trim();

  json[before] = {};

  body.split(';').filter(Boolean).forEach(function(decl) {
    var keyEnd = decl.indexOf(':');
    var key = decl.slice(0, keyEnd).trim();
    var val = decl.slice(keyEnd+1, decl.length).trim();
    json[before][key] = val;
  });
}

var json = {};
var res = balanced('{', '}', css);

if (!json.length) {
  hicks(res, json);
}

while ((res.post.indexOf('{') !== -1) && (res.post.indexOf('}') !== -1)) {
  res = balanced('{', '}', res.post);
  hicks(res, json);
}

console.log(JSON.stringify(json, 0, 2));
```

outputs

```
{
  ":root": {
    "clr": "#edc6ea",
    "radius": "5px"
  },
  "@mixin border-radius($radius)": {
    "-webkit-border-radius": "$radius",
    "-o-border-radius": "$radius",
    "border-radius": "$radius"
  },
  "ul": {
    "padding": "123px",
    "font-family": "Arial"
  },
  "ul li > div": {
    "border-radius": "12px",
    "font-size": "size",
    "color": "clr"
  },
  "ul li > div a.btn .big": {
    "color": "black"
  },
  "ul li > div a.click .something .bg": {
    "border-radius": "radius",
    "background": "teal"
  }
}
```
